// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/Cfg_Scene_Patrol.proto

#include "config/Cfg_Scene_Patrol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_config_2fCfg_5fScene_5fPatrol_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_config_2fCfg_5fScene_5fPatrol_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto;
class Cfg_Scene_Patrol_Row_patrol_dataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Cfg_Scene_Patrol_Row_patrol_data> _instance;
} _Cfg_Scene_Patrol_Row_patrol_data_default_instance_;
class Cfg_Scene_Patrol_RowDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Cfg_Scene_Patrol_Row> _instance;
} _Cfg_Scene_Patrol_Row_default_instance_;
class Cfg_Scene_PatrolDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Cfg_Scene_Patrol> _instance;
} _Cfg_Scene_Patrol_default_instance_;
static void InitDefaultsscc_info_Cfg_Scene_Patrol_config_2fCfg_5fScene_5fPatrol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Cfg_Scene_Patrol_default_instance_;
    new (ptr) ::Cfg_Scene_Patrol();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Cfg_Scene_Patrol::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Cfg_Scene_Patrol_config_2fCfg_5fScene_5fPatrol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Cfg_Scene_Patrol_config_2fCfg_5fScene_5fPatrol_2eproto}, {
      &scc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto.base,}};

static void InitDefaultsscc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Cfg_Scene_Patrol_Row_default_instance_;
    new (ptr) ::Cfg_Scene_Patrol_Row();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Cfg_Scene_Patrol_Row::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto}, {
      &scc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto.base,}};

static void InitDefaultsscc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Cfg_Scene_Patrol_Row_patrol_data_default_instance_;
    new (ptr) ::Cfg_Scene_Patrol_Row_patrol_data();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Cfg_Scene_Patrol_Row_patrol_data::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_config_2fCfg_5fScene_5fPatrol_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_config_2fCfg_5fScene_5fPatrol_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_config_2fCfg_5fScene_5fPatrol_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_config_2fCfg_5fScene_5fPatrol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row_patrol_data, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row_patrol_data, x_),
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row_patrol_data, y_),
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row_patrol_data, wait_ms_min_),
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row_patrol_data, wait_ms_max_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row, idmap_),
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row, patrol_idx_),
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row, patrol_type_),
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol_Row, data_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Cfg_Scene_Patrol, rows_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Cfg_Scene_Patrol_Row_patrol_data)},
  { 9, -1, sizeof(::Cfg_Scene_Patrol_Row)},
  { 18, -1, sizeof(::Cfg_Scene_Patrol)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Cfg_Scene_Patrol_Row_patrol_data_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Cfg_Scene_Patrol_Row_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Cfg_Scene_Patrol_default_instance_),
};

const char descriptor_table_protodef_config_2fCfg_5fScene_5fPatrol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035config/Cfg_Scene_Patrol.proto\"\367\001\n\020Cfg_"
  "Scene_Patrol\022#\n\004rows\030\001 \003(\0132\025.Cfg_Scene_P"
  "atrol.Row\032\275\001\n\003Row\022\r\n\005idmap\030\001 \001(\r\022\022\n\npatr"
  "ol_idx\030\002 \001(\r\022\023\n\013patrol_type\030\004 \001(\r\022/\n\004dat"
  "a\030\005 \003(\0132!.Cfg_Scene_Patrol.Row.patrol_da"
  "ta\032M\n\013patrol_data\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022"
  "\023\n\013wait_ms_min\030\003 \001(\r\022\023\n\013wait_ms_max\030\004 \001("
  "\rB\002H\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_sccs[3] = {
  &scc_info_Cfg_Scene_Patrol_config_2fCfg_5fScene_5fPatrol_2eproto.base,
  &scc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto.base,
  &scc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_once;
static bool descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto = {
  &descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_initialized, descriptor_table_protodef_config_2fCfg_5fScene_5fPatrol_2eproto, "config/Cfg_Scene_Patrol.proto", 293,
  &descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_once, descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_sccs, descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_config_2fCfg_5fScene_5fPatrol_2eproto::offsets,
  file_level_metadata_config_2fCfg_5fScene_5fPatrol_2eproto, 3, file_level_enum_descriptors_config_2fCfg_5fScene_5fPatrol_2eproto, file_level_service_descriptors_config_2fCfg_5fScene_5fPatrol_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_config_2fCfg_5fScene_5fPatrol_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_config_2fCfg_5fScene_5fPatrol_2eproto), true);

// ===================================================================

void Cfg_Scene_Patrol_Row_patrol_data::InitAsDefaultInstance() {
}
class Cfg_Scene_Patrol_Row_patrol_data::_Internal {
 public:
};

Cfg_Scene_Patrol_Row_patrol_data::Cfg_Scene_Patrol_Row_patrol_data()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_Scene_Patrol.Row.patrol_data)
}
Cfg_Scene_Patrol_Row_patrol_data::Cfg_Scene_Patrol_Row_patrol_data(const Cfg_Scene_Patrol_Row_patrol_data& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&wait_ms_max_) -
    reinterpret_cast<char*>(&x_)) + sizeof(wait_ms_max_));
  // @@protoc_insertion_point(copy_constructor:Cfg_Scene_Patrol.Row.patrol_data)
}

void Cfg_Scene_Patrol_Row_patrol_data::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&wait_ms_max_) -
      reinterpret_cast<char*>(&x_)) + sizeof(wait_ms_max_));
}

Cfg_Scene_Patrol_Row_patrol_data::~Cfg_Scene_Patrol_Row_patrol_data() {
  // @@protoc_insertion_point(destructor:Cfg_Scene_Patrol.Row.patrol_data)
  SharedDtor();
}

void Cfg_Scene_Patrol_Row_patrol_data::SharedDtor() {
}

void Cfg_Scene_Patrol_Row_patrol_data::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Cfg_Scene_Patrol_Row_patrol_data& Cfg_Scene_Patrol_Row_patrol_data::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Cfg_Scene_Patrol_Row_patrol_data_config_2fCfg_5fScene_5fPatrol_2eproto.base);
  return *internal_default_instance();
}


void Cfg_Scene_Patrol_Row_patrol_data::InternalSwap(Cfg_Scene_Patrol_Row_patrol_data* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Cfg_Scene_Patrol_Row_patrol_data::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Cfg_Scene_Patrol_Row::InitAsDefaultInstance() {
}
class Cfg_Scene_Patrol_Row::_Internal {
 public:
};

Cfg_Scene_Patrol_Row::Cfg_Scene_Patrol_Row()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_Scene_Patrol.Row)
}
Cfg_Scene_Patrol_Row::Cfg_Scene_Patrol_Row(const Cfg_Scene_Patrol_Row& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&idmap_, &from.idmap_,
    static_cast<size_t>(reinterpret_cast<char*>(&patrol_type_) -
    reinterpret_cast<char*>(&idmap_)) + sizeof(patrol_type_));
  // @@protoc_insertion_point(copy_constructor:Cfg_Scene_Patrol.Row)
}

void Cfg_Scene_Patrol_Row::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto.base);
  ::memset(&idmap_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&patrol_type_) -
      reinterpret_cast<char*>(&idmap_)) + sizeof(patrol_type_));
}

Cfg_Scene_Patrol_Row::~Cfg_Scene_Patrol_Row() {
  // @@protoc_insertion_point(destructor:Cfg_Scene_Patrol.Row)
  SharedDtor();
}

void Cfg_Scene_Patrol_Row::SharedDtor() {
}

void Cfg_Scene_Patrol_Row::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Cfg_Scene_Patrol_Row& Cfg_Scene_Patrol_Row::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Cfg_Scene_Patrol_Row_config_2fCfg_5fScene_5fPatrol_2eproto.base);
  return *internal_default_instance();
}


void Cfg_Scene_Patrol_Row::InternalSwap(Cfg_Scene_Patrol_Row* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Cfg_Scene_Patrol_Row::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Cfg_Scene_Patrol::InitAsDefaultInstance() {
}
class Cfg_Scene_Patrol::_Internal {
 public:
};

Cfg_Scene_Patrol::Cfg_Scene_Patrol()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_Scene_Patrol)
}
Cfg_Scene_Patrol::Cfg_Scene_Patrol(const Cfg_Scene_Patrol& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      rows_(from.rows_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Cfg_Scene_Patrol)
}

void Cfg_Scene_Patrol::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Cfg_Scene_Patrol_config_2fCfg_5fScene_5fPatrol_2eproto.base);
}

Cfg_Scene_Patrol::~Cfg_Scene_Patrol() {
  // @@protoc_insertion_point(destructor:Cfg_Scene_Patrol)
  SharedDtor();
}

void Cfg_Scene_Patrol::SharedDtor() {
}

void Cfg_Scene_Patrol::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Cfg_Scene_Patrol& Cfg_Scene_Patrol::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Cfg_Scene_Patrol_config_2fCfg_5fScene_5fPatrol_2eproto.base);
  return *internal_default_instance();
}


void Cfg_Scene_Patrol::InternalSwap(Cfg_Scene_Patrol* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Cfg_Scene_Patrol::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Cfg_Scene_Patrol_Row_patrol_data* Arena::CreateMaybeMessage< ::Cfg_Scene_Patrol_Row_patrol_data >(Arena* arena) {
  return Arena::CreateInternal< ::Cfg_Scene_Patrol_Row_patrol_data >(arena);
}
template<> PROTOBUF_NOINLINE ::Cfg_Scene_Patrol_Row* Arena::CreateMaybeMessage< ::Cfg_Scene_Patrol_Row >(Arena* arena) {
  return Arena::CreateInternal< ::Cfg_Scene_Patrol_Row >(arena);
}
template<> PROTOBUF_NOINLINE ::Cfg_Scene_Patrol* Arena::CreateMaybeMessage< ::Cfg_Scene_Patrol >(Arena* arena) {
  return Arena::CreateInternal< ::Cfg_Scene_Patrol >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
