// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/Cfg_Skill.proto

#ifndef PROTOBUF_config_2fCfg_5fSkill_2eproto__INCLUDED
#define PROTOBUF_config_2fCfg_5fSkill_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "common/AttribChangeDataProto.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_config_2fCfg_5fSkill_2eproto();
void protobuf_InitDefaults_config_2fCfg_5fSkill_2eproto();
void protobuf_AssignDesc_config_2fCfg_5fSkill_2eproto();
void protobuf_ShutdownFile_config_2fCfg_5fSkill_2eproto();

class Cfg_Skill;
class Cfg_Skill_Row;

// ===================================================================

class Cfg_Skill_Row : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Cfg_Skill.Row) */ {
 public:
  Cfg_Skill_Row();
  virtual ~Cfg_Skill_Row();

  Cfg_Skill_Row(const Cfg_Skill_Row& from);

  inline Cfg_Skill_Row& operator=(const Cfg_Skill_Row& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Cfg_Skill_Row& default_instance();

  static const Cfg_Skill_Row* internal_default_instance();

  void Swap(Cfg_Skill_Row* other);

  // implements Message ----------------------------------------------

  inline Cfg_Skill_Row* New() const { return New(NULL); }

  Cfg_Skill_Row* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Cfg_Skill_Row* other);
  void UnsafeMergeFrom(const Cfg_Skill_Row& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // optional uint32 sort = 2;
  void clear_sort();
  static const int kSortFieldNumber = 2;
  ::google::protobuf::uint32 sort() const;
  void set_sort(::google::protobuf::uint32 value);

  // optional uint32 level = 3;
  void clear_level();
  static const int kLevelFieldNumber = 3;
  ::google::protobuf::uint32 level() const;
  void set_level(::google::protobuf::uint32 value);

  // optional uint32 type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // optional string name = 5;
  void clear_name();
  static const int kNameFieldNumber = 5;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional uint32 learn_level = 6;
  void clear_learn_level();
  static const int kLearnLevelFieldNumber = 6;
  ::google::protobuf::uint32 learn_level() const;
  void set_learn_level(::google::protobuf::uint32 value);

  // optional uint32 prof_req = 7;
  void clear_prof_req();
  static const int kProfReqFieldNumber = 7;
  ::google::protobuf::uint32 prof_req() const;
  void set_prof_req(::google::protobuf::uint32 value);

  // optional uint32 skillid_req = 8;
  void clear_skillid_req();
  static const int kSkillidReqFieldNumber = 8;
  ::google::protobuf::uint32 skillid_req() const;
  void set_skillid_req(::google::protobuf::uint32 value);

  // optional uint32 use_itemtype = 9;
  void clear_use_itemtype();
  static const int kUseItemtypeFieldNumber = 9;
  ::google::protobuf::uint32 use_itemtype() const;
  void set_use_itemtype(::google::protobuf::uint32 value);

  // optional int32 use_mp = 10;
  void clear_use_mp();
  static const int kUseMpFieldNumber = 10;
  ::google::protobuf::int32 use_mp() const;
  void set_use_mp(::google::protobuf::int32 value);

  // optional int32 use_hp = 11;
  void clear_use_hp();
  static const int kUseHpFieldNumber = 11;
  ::google::protobuf::int32 use_hp() const;
  void set_use_hp(::google::protobuf::int32 value);

  // optional uint32 use_needstatus = 12;
  void clear_use_needstatus();
  static const int kUseNeedstatusFieldNumber = 12;
  ::google::protobuf::uint32 use_needstatus() const;
  void set_use_needstatus(::google::protobuf::uint32 value);

  // optional uint32 power = 13;
  void clear_power();
  static const int kPowerFieldNumber = 13;
  ::google::protobuf::uint32 power() const;
  void set_power(::google::protobuf::uint32 value);

  // optional uint32 max_power = 14;
  void clear_max_power();
  static const int kMaxPowerFieldNumber = 14;
  ::google::protobuf::uint32 max_power() const;
  void set_max_power(::google::protobuf::uint32 value);

  // optional uint32 power_addition = 15;
  void clear_power_addition();
  static const int kPowerAdditionFieldNumber = 15;
  ::google::protobuf::uint32 power_addition() const;
  void set_power_addition(::google::protobuf::uint32 value);

  // optional uint32 data = 16;
  void clear_data();
  static const int kDataFieldNumber = 16;
  ::google::protobuf::uint32 data() const;
  void set_data(::google::protobuf::uint32 value);

  // optional uint32 intone_ms = 17;
  void clear_intone_ms();
  static const int kIntoneMsFieldNumber = 17;
  ::google::protobuf::uint32 intone_ms() const;
  void set_intone_ms(::google::protobuf::uint32 value);

  // optional uint32 apply_times = 18;
  void clear_apply_times();
  static const int kApplyTimesFieldNumber = 18;
  ::google::protobuf::uint32 apply_times() const;
  void set_apply_times(::google::protobuf::uint32 value);

  // optional uint32 apply_ms = 19;
  void clear_apply_ms();
  static const int kApplyMsFieldNumber = 19;
  ::google::protobuf::uint32 apply_ms() const;
  void set_apply_ms(::google::protobuf::uint32 value);

  // optional uint32 apply_adj_ms = 20;
  void clear_apply_adj_ms();
  static const int kApplyAdjMsFieldNumber = 20;
  ::google::protobuf::uint32 apply_adj_ms() const;
  void set_apply_adj_ms(::google::protobuf::uint32 value);

  // optional uint32 stun_ms = 21;
  void clear_stun_ms();
  static const int kStunMsFieldNumber = 21;
  ::google::protobuf::uint32 stun_ms() const;
  void set_stun_ms(::google::protobuf::uint32 value);

  // optional uint32 cd_sec = 22;
  void clear_cd_sec();
  static const int kCdSecFieldNumber = 22;
  ::google::protobuf::uint32 cd_sec() const;
  void set_cd_sec(::google::protobuf::uint32 value);

  // optional uint32 cd_type = 23;
  void clear_cd_type();
  static const int kCdTypeFieldNumber = 23;
  ::google::protobuf::uint32 cd_type() const;
  void set_cd_type(::google::protobuf::uint32 value);

  // optional uint32 hit_type = 24;
  void clear_hit_type();
  static const int kHitTypeFieldNumber = 24;
  ::google::protobuf::uint32 hit_type() const;
  void set_hit_type(::google::protobuf::uint32 value);

  // optional float distance = 25;
  void clear_distance();
  static const int kDistanceFieldNumber = 25;
  float distance() const;
  void set_distance(float value);

  // optional float max_distance = 26;
  void clear_max_distance();
  static const int kMaxDistanceFieldNumber = 26;
  float max_distance() const;
  void set_max_distance(float value);

  // optional float range = 27;
  void clear_range();
  static const int kRangeFieldNumber = 27;
  float range() const;
  void set_range(float value);

  // optional float width = 28;
  void clear_width();
  static const int kWidthFieldNumber = 28;
  float width() const;
  void set_width(float value);

  // optional uint32 cast_type = 29;
  void clear_cast_type();
  static const int kCastTypeFieldNumber = 29;
  ::google::protobuf::uint32 cast_type() const;
  void set_cast_type(::google::protobuf::uint32 value);

  // optional uint32 flag = 30;
  void clear_flag();
  static const int kFlagFieldNumber = 30;
  ::google::protobuf::uint32 flag() const;
  void set_flag(::google::protobuf::uint32 value);

  // optional uint32 damage_flag = 31;
  void clear_damage_flag();
  static const int kDamageFlagFieldNumber = 31;
  ::google::protobuf::uint32 damage_flag() const;
  void set_damage_flag(::google::protobuf::uint32 value);

  // optional uint32 damage_shape = 32;
  void clear_damage_shape();
  static const int kDamageShapeFieldNumber = 32;
  ::google::protobuf::uint32 damage_shape() const;
  void set_damage_shape(::google::protobuf::uint32 value);

  // optional uint32 bulletid = 33;
  void clear_bulletid();
  static const int kBulletidFieldNumber = 33;
  ::google::protobuf::uint32 bulletid() const;
  void set_bulletid(::google::protobuf::uint32 value);

  // optional uint64 scriptid = 34;
  void clear_scriptid();
  static const int kScriptidFieldNumber = 34;
  ::google::protobuf::uint64 scriptid() const;
  void set_scriptid(::google::protobuf::uint64 value);

  // optional bool isdebug = 35;
  void clear_isdebug();
  static const int kIsdebugFieldNumber = 35;
  bool isdebug() const;
  void set_isdebug(bool value);

  // repeated .AttribChangeDataProto attrib_change_list = 36;
  int attrib_change_list_size() const;
  void clear_attrib_change_list();
  static const int kAttribChangeListFieldNumber = 36;
  const ::AttribChangeDataProto& attrib_change_list(int index) const;
  ::AttribChangeDataProto* mutable_attrib_change_list(int index);
  ::AttribChangeDataProto* add_attrib_change_list();
  ::google::protobuf::RepeatedPtrField< ::AttribChangeDataProto >*
      mutable_attrib_change_list();
  const ::google::protobuf::RepeatedPtrField< ::AttribChangeDataProto >&
      attrib_change_list() const;

  // @@protoc_insertion_point(class_scope:Cfg_Skill.Row)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::AttribChangeDataProto > attrib_change_list_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 sort_;
  ::google::protobuf::uint32 level_;
  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 learn_level_;
  ::google::protobuf::uint32 prof_req_;
  ::google::protobuf::uint32 skillid_req_;
  ::google::protobuf::uint32 use_itemtype_;
  ::google::protobuf::int32 use_mp_;
  ::google::protobuf::int32 use_hp_;
  ::google::protobuf::uint32 use_needstatus_;
  ::google::protobuf::uint32 power_;
  ::google::protobuf::uint32 max_power_;
  ::google::protobuf::uint32 power_addition_;
  ::google::protobuf::uint32 data_;
  ::google::protobuf::uint32 intone_ms_;
  ::google::protobuf::uint32 apply_times_;
  ::google::protobuf::uint32 apply_ms_;
  ::google::protobuf::uint32 apply_adj_ms_;
  ::google::protobuf::uint32 stun_ms_;
  ::google::protobuf::uint32 cd_sec_;
  ::google::protobuf::uint32 cd_type_;
  ::google::protobuf::uint32 hit_type_;
  float distance_;
  float max_distance_;
  float range_;
  float width_;
  ::google::protobuf::uint32 cast_type_;
  ::google::protobuf::uint32 flag_;
  ::google::protobuf::uint32 damage_flag_;
  ::google::protobuf::uint32 damage_shape_;
  ::google::protobuf::uint32 bulletid_;
  ::google::protobuf::uint64 scriptid_;
  bool isdebug_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_config_2fCfg_5fSkill_2eproto_impl();
  friend void  protobuf_AddDesc_config_2fCfg_5fSkill_2eproto_impl();
  friend void protobuf_AssignDesc_config_2fCfg_5fSkill_2eproto();
  friend void protobuf_ShutdownFile_config_2fCfg_5fSkill_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Cfg_Skill_Row> Cfg_Skill_Row_default_instance_;

// -------------------------------------------------------------------

class Cfg_Skill : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Cfg_Skill) */ {
 public:
  Cfg_Skill();
  virtual ~Cfg_Skill();

  Cfg_Skill(const Cfg_Skill& from);

  inline Cfg_Skill& operator=(const Cfg_Skill& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Cfg_Skill& default_instance();

  static const Cfg_Skill* internal_default_instance();

  void Swap(Cfg_Skill* other);

  // implements Message ----------------------------------------------

  inline Cfg_Skill* New() const { return New(NULL); }

  Cfg_Skill* New(::google::protobuf::Arena* arena) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Cfg_Skill* other);
  void UnsafeMergeFrom(const Cfg_Skill& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Cfg_Skill_Row Row;

  // accessors -------------------------------------------------------

  // repeated .Cfg_Skill.Row rows = 1;
  int rows_size() const;
  void clear_rows();
  static const int kRowsFieldNumber = 1;
  const ::Cfg_Skill_Row& rows(int index) const;
  ::Cfg_Skill_Row* mutable_rows(int index);
  ::Cfg_Skill_Row* add_rows();
  ::google::protobuf::RepeatedPtrField< ::Cfg_Skill_Row >*
      mutable_rows();
  const ::google::protobuf::RepeatedPtrField< ::Cfg_Skill_Row >&
      rows() const;

  // @@protoc_insertion_point(class_scope:Cfg_Skill)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Cfg_Skill_Row > rows_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_config_2fCfg_5fSkill_2eproto_impl();
  friend void  protobuf_AddDesc_config_2fCfg_5fSkill_2eproto_impl();
  friend void protobuf_AssignDesc_config_2fCfg_5fSkill_2eproto();
  friend void protobuf_ShutdownFile_config_2fCfg_5fSkill_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Cfg_Skill> Cfg_Skill_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Cfg_Skill_Row

// optional uint32 id = 1;
inline void Cfg_Skill_Row::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::id() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.id)
  return id_;
}
inline void Cfg_Skill_Row::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.id)
}

// optional uint32 sort = 2;
inline void Cfg_Skill_Row::clear_sort() {
  sort_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::sort() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.sort)
  return sort_;
}
inline void Cfg_Skill_Row::set_sort(::google::protobuf::uint32 value) {
  
  sort_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.sort)
}

// optional uint32 level = 3;
inline void Cfg_Skill_Row::clear_level() {
  level_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::level() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.level)
  return level_;
}
inline void Cfg_Skill_Row::set_level(::google::protobuf::uint32 value) {
  
  level_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.level)
}

// optional uint32 type = 4;
inline void Cfg_Skill_Row::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::type() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.type)
  return type_;
}
inline void Cfg_Skill_Row::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.type)
}

// optional string name = 5;
inline void Cfg_Skill_Row::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Cfg_Skill_Row::name() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Cfg_Skill_Row::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.name)
}
inline void Cfg_Skill_Row::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Cfg_Skill.Row.name)
}
inline void Cfg_Skill_Row::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Cfg_Skill.Row.name)
}
inline ::std::string* Cfg_Skill_Row::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Cfg_Skill.Row.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Cfg_Skill_Row::release_name() {
  // @@protoc_insertion_point(field_release:Cfg_Skill.Row.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Cfg_Skill_Row::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Cfg_Skill.Row.name)
}

// optional uint32 learn_level = 6;
inline void Cfg_Skill_Row::clear_learn_level() {
  learn_level_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::learn_level() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.learn_level)
  return learn_level_;
}
inline void Cfg_Skill_Row::set_learn_level(::google::protobuf::uint32 value) {
  
  learn_level_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.learn_level)
}

// optional uint32 prof_req = 7;
inline void Cfg_Skill_Row::clear_prof_req() {
  prof_req_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::prof_req() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.prof_req)
  return prof_req_;
}
inline void Cfg_Skill_Row::set_prof_req(::google::protobuf::uint32 value) {
  
  prof_req_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.prof_req)
}

// optional uint32 skillid_req = 8;
inline void Cfg_Skill_Row::clear_skillid_req() {
  skillid_req_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::skillid_req() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.skillid_req)
  return skillid_req_;
}
inline void Cfg_Skill_Row::set_skillid_req(::google::protobuf::uint32 value) {
  
  skillid_req_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.skillid_req)
}

// optional uint32 use_itemtype = 9;
inline void Cfg_Skill_Row::clear_use_itemtype() {
  use_itemtype_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::use_itemtype() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.use_itemtype)
  return use_itemtype_;
}
inline void Cfg_Skill_Row::set_use_itemtype(::google::protobuf::uint32 value) {
  
  use_itemtype_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.use_itemtype)
}

// optional int32 use_mp = 10;
inline void Cfg_Skill_Row::clear_use_mp() {
  use_mp_ = 0;
}
inline ::google::protobuf::int32 Cfg_Skill_Row::use_mp() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.use_mp)
  return use_mp_;
}
inline void Cfg_Skill_Row::set_use_mp(::google::protobuf::int32 value) {
  
  use_mp_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.use_mp)
}

// optional int32 use_hp = 11;
inline void Cfg_Skill_Row::clear_use_hp() {
  use_hp_ = 0;
}
inline ::google::protobuf::int32 Cfg_Skill_Row::use_hp() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.use_hp)
  return use_hp_;
}
inline void Cfg_Skill_Row::set_use_hp(::google::protobuf::int32 value) {
  
  use_hp_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.use_hp)
}

// optional uint32 use_needstatus = 12;
inline void Cfg_Skill_Row::clear_use_needstatus() {
  use_needstatus_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::use_needstatus() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.use_needstatus)
  return use_needstatus_;
}
inline void Cfg_Skill_Row::set_use_needstatus(::google::protobuf::uint32 value) {
  
  use_needstatus_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.use_needstatus)
}

// optional uint32 power = 13;
inline void Cfg_Skill_Row::clear_power() {
  power_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::power() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.power)
  return power_;
}
inline void Cfg_Skill_Row::set_power(::google::protobuf::uint32 value) {
  
  power_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.power)
}

// optional uint32 max_power = 14;
inline void Cfg_Skill_Row::clear_max_power() {
  max_power_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::max_power() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.max_power)
  return max_power_;
}
inline void Cfg_Skill_Row::set_max_power(::google::protobuf::uint32 value) {
  
  max_power_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.max_power)
}

// optional uint32 power_addition = 15;
inline void Cfg_Skill_Row::clear_power_addition() {
  power_addition_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::power_addition() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.power_addition)
  return power_addition_;
}
inline void Cfg_Skill_Row::set_power_addition(::google::protobuf::uint32 value) {
  
  power_addition_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.power_addition)
}

// optional uint32 data = 16;
inline void Cfg_Skill_Row::clear_data() {
  data_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::data() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.data)
  return data_;
}
inline void Cfg_Skill_Row::set_data(::google::protobuf::uint32 value) {
  
  data_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.data)
}

// optional uint32 intone_ms = 17;
inline void Cfg_Skill_Row::clear_intone_ms() {
  intone_ms_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::intone_ms() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.intone_ms)
  return intone_ms_;
}
inline void Cfg_Skill_Row::set_intone_ms(::google::protobuf::uint32 value) {
  
  intone_ms_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.intone_ms)
}

// optional uint32 apply_times = 18;
inline void Cfg_Skill_Row::clear_apply_times() {
  apply_times_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::apply_times() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.apply_times)
  return apply_times_;
}
inline void Cfg_Skill_Row::set_apply_times(::google::protobuf::uint32 value) {
  
  apply_times_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.apply_times)
}

// optional uint32 apply_ms = 19;
inline void Cfg_Skill_Row::clear_apply_ms() {
  apply_ms_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::apply_ms() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.apply_ms)
  return apply_ms_;
}
inline void Cfg_Skill_Row::set_apply_ms(::google::protobuf::uint32 value) {
  
  apply_ms_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.apply_ms)
}

// optional uint32 apply_adj_ms = 20;
inline void Cfg_Skill_Row::clear_apply_adj_ms() {
  apply_adj_ms_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::apply_adj_ms() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.apply_adj_ms)
  return apply_adj_ms_;
}
inline void Cfg_Skill_Row::set_apply_adj_ms(::google::protobuf::uint32 value) {
  
  apply_adj_ms_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.apply_adj_ms)
}

// optional uint32 stun_ms = 21;
inline void Cfg_Skill_Row::clear_stun_ms() {
  stun_ms_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::stun_ms() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.stun_ms)
  return stun_ms_;
}
inline void Cfg_Skill_Row::set_stun_ms(::google::protobuf::uint32 value) {
  
  stun_ms_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.stun_ms)
}

// optional uint32 cd_sec = 22;
inline void Cfg_Skill_Row::clear_cd_sec() {
  cd_sec_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::cd_sec() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.cd_sec)
  return cd_sec_;
}
inline void Cfg_Skill_Row::set_cd_sec(::google::protobuf::uint32 value) {
  
  cd_sec_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.cd_sec)
}

// optional uint32 cd_type = 23;
inline void Cfg_Skill_Row::clear_cd_type() {
  cd_type_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::cd_type() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.cd_type)
  return cd_type_;
}
inline void Cfg_Skill_Row::set_cd_type(::google::protobuf::uint32 value) {
  
  cd_type_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.cd_type)
}

// optional uint32 hit_type = 24;
inline void Cfg_Skill_Row::clear_hit_type() {
  hit_type_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::hit_type() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.hit_type)
  return hit_type_;
}
inline void Cfg_Skill_Row::set_hit_type(::google::protobuf::uint32 value) {
  
  hit_type_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.hit_type)
}

// optional float distance = 25;
inline void Cfg_Skill_Row::clear_distance() {
  distance_ = 0;
}
inline float Cfg_Skill_Row::distance() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.distance)
  return distance_;
}
inline void Cfg_Skill_Row::set_distance(float value) {
  
  distance_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.distance)
}

// optional float max_distance = 26;
inline void Cfg_Skill_Row::clear_max_distance() {
  max_distance_ = 0;
}
inline float Cfg_Skill_Row::max_distance() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.max_distance)
  return max_distance_;
}
inline void Cfg_Skill_Row::set_max_distance(float value) {
  
  max_distance_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.max_distance)
}

// optional float range = 27;
inline void Cfg_Skill_Row::clear_range() {
  range_ = 0;
}
inline float Cfg_Skill_Row::range() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.range)
  return range_;
}
inline void Cfg_Skill_Row::set_range(float value) {
  
  range_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.range)
}

// optional float width = 28;
inline void Cfg_Skill_Row::clear_width() {
  width_ = 0;
}
inline float Cfg_Skill_Row::width() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.width)
  return width_;
}
inline void Cfg_Skill_Row::set_width(float value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.width)
}

// optional uint32 cast_type = 29;
inline void Cfg_Skill_Row::clear_cast_type() {
  cast_type_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::cast_type() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.cast_type)
  return cast_type_;
}
inline void Cfg_Skill_Row::set_cast_type(::google::protobuf::uint32 value) {
  
  cast_type_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.cast_type)
}

// optional uint32 flag = 30;
inline void Cfg_Skill_Row::clear_flag() {
  flag_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::flag() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.flag)
  return flag_;
}
inline void Cfg_Skill_Row::set_flag(::google::protobuf::uint32 value) {
  
  flag_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.flag)
}

// optional uint32 damage_flag = 31;
inline void Cfg_Skill_Row::clear_damage_flag() {
  damage_flag_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::damage_flag() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.damage_flag)
  return damage_flag_;
}
inline void Cfg_Skill_Row::set_damage_flag(::google::protobuf::uint32 value) {
  
  damage_flag_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.damage_flag)
}

// optional uint32 damage_shape = 32;
inline void Cfg_Skill_Row::clear_damage_shape() {
  damage_shape_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::damage_shape() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.damage_shape)
  return damage_shape_;
}
inline void Cfg_Skill_Row::set_damage_shape(::google::protobuf::uint32 value) {
  
  damage_shape_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.damage_shape)
}

// optional uint32 bulletid = 33;
inline void Cfg_Skill_Row::clear_bulletid() {
  bulletid_ = 0u;
}
inline ::google::protobuf::uint32 Cfg_Skill_Row::bulletid() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.bulletid)
  return bulletid_;
}
inline void Cfg_Skill_Row::set_bulletid(::google::protobuf::uint32 value) {
  
  bulletid_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.bulletid)
}

// optional uint64 scriptid = 34;
inline void Cfg_Skill_Row::clear_scriptid() {
  scriptid_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Cfg_Skill_Row::scriptid() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.scriptid)
  return scriptid_;
}
inline void Cfg_Skill_Row::set_scriptid(::google::protobuf::uint64 value) {
  
  scriptid_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.scriptid)
}

// optional bool isdebug = 35;
inline void Cfg_Skill_Row::clear_isdebug() {
  isdebug_ = false;
}
inline bool Cfg_Skill_Row::isdebug() const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.isdebug)
  return isdebug_;
}
inline void Cfg_Skill_Row::set_isdebug(bool value) {
  
  isdebug_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Skill.Row.isdebug)
}

// repeated .AttribChangeDataProto attrib_change_list = 36;
inline int Cfg_Skill_Row::attrib_change_list_size() const {
  return attrib_change_list_.size();
}
inline void Cfg_Skill_Row::clear_attrib_change_list() {
  attrib_change_list_.Clear();
}
inline const ::AttribChangeDataProto& Cfg_Skill_Row::attrib_change_list(int index) const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.Row.attrib_change_list)
  return attrib_change_list_.Get(index);
}
inline ::AttribChangeDataProto* Cfg_Skill_Row::mutable_attrib_change_list(int index) {
  // @@protoc_insertion_point(field_mutable:Cfg_Skill.Row.attrib_change_list)
  return attrib_change_list_.Mutable(index);
}
inline ::AttribChangeDataProto* Cfg_Skill_Row::add_attrib_change_list() {
  // @@protoc_insertion_point(field_add:Cfg_Skill.Row.attrib_change_list)
  return attrib_change_list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::AttribChangeDataProto >*
Cfg_Skill_Row::mutable_attrib_change_list() {
  // @@protoc_insertion_point(field_mutable_list:Cfg_Skill.Row.attrib_change_list)
  return &attrib_change_list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::AttribChangeDataProto >&
Cfg_Skill_Row::attrib_change_list() const {
  // @@protoc_insertion_point(field_list:Cfg_Skill.Row.attrib_change_list)
  return attrib_change_list_;
}

inline const Cfg_Skill_Row* Cfg_Skill_Row::internal_default_instance() {
  return &Cfg_Skill_Row_default_instance_.get();
}
// -------------------------------------------------------------------

// Cfg_Skill

// repeated .Cfg_Skill.Row rows = 1;
inline int Cfg_Skill::rows_size() const {
  return rows_.size();
}
inline void Cfg_Skill::clear_rows() {
  rows_.Clear();
}
inline const ::Cfg_Skill_Row& Cfg_Skill::rows(int index) const {
  // @@protoc_insertion_point(field_get:Cfg_Skill.rows)
  return rows_.Get(index);
}
inline ::Cfg_Skill_Row* Cfg_Skill::mutable_rows(int index) {
  // @@protoc_insertion_point(field_mutable:Cfg_Skill.rows)
  return rows_.Mutable(index);
}
inline ::Cfg_Skill_Row* Cfg_Skill::add_rows() {
  // @@protoc_insertion_point(field_add:Cfg_Skill.rows)
  return rows_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Cfg_Skill_Row >*
Cfg_Skill::mutable_rows() {
  // @@protoc_insertion_point(field_mutable_list:Cfg_Skill.rows)
  return &rows_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Cfg_Skill_Row >&
Cfg_Skill::rows() const {
  // @@protoc_insertion_point(field_list:Cfg_Skill.rows)
  return rows_;
}

inline const Cfg_Skill* Cfg_Skill::internal_default_instance() {
  return &Cfg_Skill_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2fCfg_5fSkill_2eproto__INCLUDED
