// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/Cfg_ItemUpgrade.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_config_2fCfg_5fItemUpgrade_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_config_2fCfg_5fItemUpgrade_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_config_2fCfg_5fItemUpgrade_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_config_2fCfg_5fItemUpgrade_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_config_2fCfg_5fItemUpgrade_2eproto;
class Cfg_ItemUpgrade;
class Cfg_ItemUpgradeDefaultTypeInternal;
extern Cfg_ItemUpgradeDefaultTypeInternal _Cfg_ItemUpgrade_default_instance_;
class Cfg_ItemUpgrade_Row;
class Cfg_ItemUpgrade_RowDefaultTypeInternal;
extern Cfg_ItemUpgrade_RowDefaultTypeInternal _Cfg_ItemUpgrade_Row_default_instance_;
class Cfg_ItemUpgrade_Row_ReqData;
class Cfg_ItemUpgrade_Row_ReqDataDefaultTypeInternal;
extern Cfg_ItemUpgrade_Row_ReqDataDefaultTypeInternal _Cfg_ItemUpgrade_Row_ReqData_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Cfg_ItemUpgrade* Arena::CreateMaybeMessage<::Cfg_ItemUpgrade>(Arena*);
template<> ::Cfg_ItemUpgrade_Row* Arena::CreateMaybeMessage<::Cfg_ItemUpgrade_Row>(Arena*);
template<> ::Cfg_ItemUpgrade_Row_ReqData* Arena::CreateMaybeMessage<::Cfg_ItemUpgrade_Row_ReqData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Cfg_ItemUpgrade_Row_ReqData :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Cfg_ItemUpgrade.Row.ReqData) */ {
 public:
  Cfg_ItemUpgrade_Row_ReqData();
  virtual ~Cfg_ItemUpgrade_Row_ReqData();

  Cfg_ItemUpgrade_Row_ReqData(const Cfg_ItemUpgrade_Row_ReqData& from);
  Cfg_ItemUpgrade_Row_ReqData(Cfg_ItemUpgrade_Row_ReqData&& from) noexcept
    : Cfg_ItemUpgrade_Row_ReqData() {
    *this = ::std::move(from);
  }

  inline Cfg_ItemUpgrade_Row_ReqData& operator=(const Cfg_ItemUpgrade_Row_ReqData& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cfg_ItemUpgrade_Row_ReqData& operator=(Cfg_ItemUpgrade_Row_ReqData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Cfg_ItemUpgrade_Row_ReqData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Cfg_ItemUpgrade_Row_ReqData* internal_default_instance() {
    return reinterpret_cast<const Cfg_ItemUpgrade_Row_ReqData*>(
               &_Cfg_ItemUpgrade_Row_ReqData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Cfg_ItemUpgrade_Row_ReqData& a, Cfg_ItemUpgrade_Row_ReqData& b) {
    a.Swap(&b);
  }
  inline void Swap(Cfg_ItemUpgrade_Row_ReqData* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Cfg_ItemUpgrade_Row_ReqData* New() const final {
    return CreateMaybeMessage<Cfg_ItemUpgrade_Row_ReqData>(nullptr);
  }

  Cfg_ItemUpgrade_Row_ReqData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Cfg_ItemUpgrade_Row_ReqData>(arena);
  }
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cfg_ItemUpgrade_Row_ReqData* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Cfg_ItemUpgrade.Row.ReqData";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_config_2fCfg_5fItemUpgrade_2eproto);
    return ::descriptor_table_config_2fCfg_5fItemUpgrade_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kReqTypeFieldNumber = 1,
    kReqNumFieldNumber = 2,
  };
  // uint32 req_type = 1;
  void clear_req_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 req_type() const;
  void set_req_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_req_type() const;
  void _internal_set_req_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 req_num = 2;
  void clear_req_num();
  ::PROTOBUF_NAMESPACE_ID::uint32 req_num() const;
  void set_req_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_req_num() const;
  void _internal_set_req_num(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Cfg_ItemUpgrade.Row.ReqData)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint32 req_type_;
  ::PROTOBUF_NAMESPACE_ID::uint32 req_num_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_config_2fCfg_5fItemUpgrade_2eproto;
};
// -------------------------------------------------------------------

class Cfg_ItemUpgrade_Row :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Cfg_ItemUpgrade.Row) */ {
 public:
  Cfg_ItemUpgrade_Row();
  virtual ~Cfg_ItemUpgrade_Row();

  Cfg_ItemUpgrade_Row(const Cfg_ItemUpgrade_Row& from);
  Cfg_ItemUpgrade_Row(Cfg_ItemUpgrade_Row&& from) noexcept
    : Cfg_ItemUpgrade_Row() {
    *this = ::std::move(from);
  }

  inline Cfg_ItemUpgrade_Row& operator=(const Cfg_ItemUpgrade_Row& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cfg_ItemUpgrade_Row& operator=(Cfg_ItemUpgrade_Row&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Cfg_ItemUpgrade_Row& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Cfg_ItemUpgrade_Row* internal_default_instance() {
    return reinterpret_cast<const Cfg_ItemUpgrade_Row*>(
               &_Cfg_ItemUpgrade_Row_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Cfg_ItemUpgrade_Row& a, Cfg_ItemUpgrade_Row& b) {
    a.Swap(&b);
  }
  inline void Swap(Cfg_ItemUpgrade_Row* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Cfg_ItemUpgrade_Row* New() const final {
    return CreateMaybeMessage<Cfg_ItemUpgrade_Row>(nullptr);
  }

  Cfg_ItemUpgrade_Row* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Cfg_ItemUpgrade_Row>(arena);
  }
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cfg_ItemUpgrade_Row* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Cfg_ItemUpgrade.Row";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_config_2fCfg_5fItemUpgrade_2eproto);
    return ::descriptor_table_config_2fCfg_5fItemUpgrade_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Cfg_ItemUpgrade_Row_ReqData ReqData;

  // accessors -------------------------------------------------------

  enum : int {
    kReqDataListFieldNumber = 10,
    kIdFieldNumber = 1,
    kSortFieldNumber = 2,
    kMainItemtypeFieldNumber = 3,
    kLevReqFieldNumber = 6,
    kSuccRateFieldNumber = 7,
    kRumorFieldNumber = 8,
  };
  // repeated .Cfg_ItemUpgrade.Row.ReqData req_data_list = 10;
  int req_data_list_size() const;
  private:
  int _internal_req_data_list_size() const;
  public:
  void clear_req_data_list();
  ::Cfg_ItemUpgrade_Row_ReqData* mutable_req_data_list(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row_ReqData >*
      mutable_req_data_list();
  private:
  const ::Cfg_ItemUpgrade_Row_ReqData& _internal_req_data_list(int index) const;
  ::Cfg_ItemUpgrade_Row_ReqData* _internal_add_req_data_list();
  public:
  const ::Cfg_ItemUpgrade_Row_ReqData& req_data_list(int index) const;
  ::Cfg_ItemUpgrade_Row_ReqData* add_req_data_list();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row_ReqData >&
      req_data_list() const;

  // uint32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 sort = 2;
  void clear_sort();
  ::PROTOBUF_NAMESPACE_ID::uint32 sort() const;
  void set_sort(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_sort() const;
  void _internal_set_sort(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 main_itemtype = 3;
  void clear_main_itemtype();
  ::PROTOBUF_NAMESPACE_ID::uint32 main_itemtype() const;
  void set_main_itemtype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_main_itemtype() const;
  void _internal_set_main_itemtype(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 lev_req = 6;
  void clear_lev_req();
  ::PROTOBUF_NAMESPACE_ID::uint32 lev_req() const;
  void set_lev_req(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_lev_req() const;
  void _internal_set_lev_req(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // float succ_rate = 7;
  void clear_succ_rate();
  float succ_rate() const;
  void set_succ_rate(float value);
  private:
  float _internal_succ_rate() const;
  void _internal_set_succ_rate(float value);
  public:

  // uint32 rumor = 8;
  void clear_rumor();
  ::PROTOBUF_NAMESPACE_ID::uint32 rumor() const;
  void set_rumor(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_rumor() const;
  void _internal_set_rumor(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Cfg_ItemUpgrade.Row)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row_ReqData > req_data_list_;
  ::PROTOBUF_NAMESPACE_ID::uint32 id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 sort_;
  ::PROTOBUF_NAMESPACE_ID::uint32 main_itemtype_;
  ::PROTOBUF_NAMESPACE_ID::uint32 lev_req_;
  float succ_rate_;
  ::PROTOBUF_NAMESPACE_ID::uint32 rumor_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_config_2fCfg_5fItemUpgrade_2eproto;
};
// -------------------------------------------------------------------

class Cfg_ItemUpgrade :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Cfg_ItemUpgrade) */ {
 public:
  Cfg_ItemUpgrade();
  virtual ~Cfg_ItemUpgrade();

  Cfg_ItemUpgrade(const Cfg_ItemUpgrade& from);
  Cfg_ItemUpgrade(Cfg_ItemUpgrade&& from) noexcept
    : Cfg_ItemUpgrade() {
    *this = ::std::move(from);
  }

  inline Cfg_ItemUpgrade& operator=(const Cfg_ItemUpgrade& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cfg_ItemUpgrade& operator=(Cfg_ItemUpgrade&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Cfg_ItemUpgrade& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Cfg_ItemUpgrade* internal_default_instance() {
    return reinterpret_cast<const Cfg_ItemUpgrade*>(
               &_Cfg_ItemUpgrade_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Cfg_ItemUpgrade& a, Cfg_ItemUpgrade& b) {
    a.Swap(&b);
  }
  inline void Swap(Cfg_ItemUpgrade* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Cfg_ItemUpgrade* New() const final {
    return CreateMaybeMessage<Cfg_ItemUpgrade>(nullptr);
  }

  Cfg_ItemUpgrade* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Cfg_ItemUpgrade>(arena);
  }
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Cfg_ItemUpgrade* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Cfg_ItemUpgrade";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_config_2fCfg_5fItemUpgrade_2eproto);
    return ::descriptor_table_config_2fCfg_5fItemUpgrade_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Cfg_ItemUpgrade_Row Row;

  // accessors -------------------------------------------------------

  enum : int {
    kRowsFieldNumber = 1,
  };
  // repeated .Cfg_ItemUpgrade.Row rows = 1;
  int rows_size() const;
  private:
  int _internal_rows_size() const;
  public:
  void clear_rows();
  ::Cfg_ItemUpgrade_Row* mutable_rows(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row >*
      mutable_rows();
  private:
  const ::Cfg_ItemUpgrade_Row& _internal_rows(int index) const;
  ::Cfg_ItemUpgrade_Row* _internal_add_rows();
  public:
  const ::Cfg_ItemUpgrade_Row& rows(int index) const;
  ::Cfg_ItemUpgrade_Row* add_rows();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row >&
      rows() const;

  // @@protoc_insertion_point(class_scope:Cfg_ItemUpgrade)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row > rows_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_config_2fCfg_5fItemUpgrade_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Cfg_ItemUpgrade_Row_ReqData

// uint32 req_type = 1;
inline void Cfg_ItemUpgrade_Row_ReqData::clear_req_type() {
  req_type_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row_ReqData::_internal_req_type() const {
  return req_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row_ReqData::req_type() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.ReqData.req_type)
  return _internal_req_type();
}
inline void Cfg_ItemUpgrade_Row_ReqData::_internal_set_req_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  req_type_ = value;
}
inline void Cfg_ItemUpgrade_Row_ReqData::set_req_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_req_type(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.ReqData.req_type)
}

// uint32 req_num = 2;
inline void Cfg_ItemUpgrade_Row_ReqData::clear_req_num() {
  req_num_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row_ReqData::_internal_req_num() const {
  return req_num_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row_ReqData::req_num() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.ReqData.req_num)
  return _internal_req_num();
}
inline void Cfg_ItemUpgrade_Row_ReqData::_internal_set_req_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  req_num_ = value;
}
inline void Cfg_ItemUpgrade_Row_ReqData::set_req_num(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_req_num(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.ReqData.req_num)
}

// -------------------------------------------------------------------

// Cfg_ItemUpgrade_Row

// uint32 id = 1;
inline void Cfg_ItemUpgrade_Row::clear_id() {
  id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::id() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.id)
  return _internal_id();
}
inline void Cfg_ItemUpgrade_Row::_internal_set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  id_ = value;
}
inline void Cfg_ItemUpgrade_Row::set_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.id)
}

// uint32 sort = 2;
inline void Cfg_ItemUpgrade_Row::clear_sort() {
  sort_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::_internal_sort() const {
  return sort_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::sort() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.sort)
  return _internal_sort();
}
inline void Cfg_ItemUpgrade_Row::_internal_set_sort(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  sort_ = value;
}
inline void Cfg_ItemUpgrade_Row::set_sort(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_sort(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.sort)
}

// uint32 main_itemtype = 3;
inline void Cfg_ItemUpgrade_Row::clear_main_itemtype() {
  main_itemtype_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::_internal_main_itemtype() const {
  return main_itemtype_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::main_itemtype() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.main_itemtype)
  return _internal_main_itemtype();
}
inline void Cfg_ItemUpgrade_Row::_internal_set_main_itemtype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  main_itemtype_ = value;
}
inline void Cfg_ItemUpgrade_Row::set_main_itemtype(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_main_itemtype(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.main_itemtype)
}

// uint32 lev_req = 6;
inline void Cfg_ItemUpgrade_Row::clear_lev_req() {
  lev_req_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::_internal_lev_req() const {
  return lev_req_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::lev_req() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.lev_req)
  return _internal_lev_req();
}
inline void Cfg_ItemUpgrade_Row::_internal_set_lev_req(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  lev_req_ = value;
}
inline void Cfg_ItemUpgrade_Row::set_lev_req(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_lev_req(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.lev_req)
}

// float succ_rate = 7;
inline void Cfg_ItemUpgrade_Row::clear_succ_rate() {
  succ_rate_ = 0;
}
inline float Cfg_ItemUpgrade_Row::_internal_succ_rate() const {
  return succ_rate_;
}
inline float Cfg_ItemUpgrade_Row::succ_rate() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.succ_rate)
  return _internal_succ_rate();
}
inline void Cfg_ItemUpgrade_Row::_internal_set_succ_rate(float value) {
  
  succ_rate_ = value;
}
inline void Cfg_ItemUpgrade_Row::set_succ_rate(float value) {
  _internal_set_succ_rate(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.succ_rate)
}

// uint32 rumor = 8;
inline void Cfg_ItemUpgrade_Row::clear_rumor() {
  rumor_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::_internal_rumor() const {
  return rumor_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Cfg_ItemUpgrade_Row::rumor() const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.rumor)
  return _internal_rumor();
}
inline void Cfg_ItemUpgrade_Row::_internal_set_rumor(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  rumor_ = value;
}
inline void Cfg_ItemUpgrade_Row::set_rumor(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_rumor(value);
  // @@protoc_insertion_point(field_set:Cfg_ItemUpgrade.Row.rumor)
}

// repeated .Cfg_ItemUpgrade.Row.ReqData req_data_list = 10;
inline int Cfg_ItemUpgrade_Row::_internal_req_data_list_size() const {
  return req_data_list_.size();
}
inline int Cfg_ItemUpgrade_Row::req_data_list_size() const {
  return _internal_req_data_list_size();
}
inline void Cfg_ItemUpgrade_Row::clear_req_data_list() {
  req_data_list_.Clear();
}
inline ::Cfg_ItemUpgrade_Row_ReqData* Cfg_ItemUpgrade_Row::mutable_req_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:Cfg_ItemUpgrade.Row.req_data_list)
  return req_data_list_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row_ReqData >*
Cfg_ItemUpgrade_Row::mutable_req_data_list() {
  // @@protoc_insertion_point(field_mutable_list:Cfg_ItemUpgrade.Row.req_data_list)
  return &req_data_list_;
}
inline const ::Cfg_ItemUpgrade_Row_ReqData& Cfg_ItemUpgrade_Row::_internal_req_data_list(int index) const {
  return req_data_list_.Get(index);
}
inline const ::Cfg_ItemUpgrade_Row_ReqData& Cfg_ItemUpgrade_Row::req_data_list(int index) const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.Row.req_data_list)
  return _internal_req_data_list(index);
}
inline ::Cfg_ItemUpgrade_Row_ReqData* Cfg_ItemUpgrade_Row::_internal_add_req_data_list() {
  return req_data_list_.Add();
}
inline ::Cfg_ItemUpgrade_Row_ReqData* Cfg_ItemUpgrade_Row::add_req_data_list() {
  // @@protoc_insertion_point(field_add:Cfg_ItemUpgrade.Row.req_data_list)
  return _internal_add_req_data_list();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row_ReqData >&
Cfg_ItemUpgrade_Row::req_data_list() const {
  // @@protoc_insertion_point(field_list:Cfg_ItemUpgrade.Row.req_data_list)
  return req_data_list_;
}

// -------------------------------------------------------------------

// Cfg_ItemUpgrade

// repeated .Cfg_ItemUpgrade.Row rows = 1;
inline int Cfg_ItemUpgrade::_internal_rows_size() const {
  return rows_.size();
}
inline int Cfg_ItemUpgrade::rows_size() const {
  return _internal_rows_size();
}
inline void Cfg_ItemUpgrade::clear_rows() {
  rows_.Clear();
}
inline ::Cfg_ItemUpgrade_Row* Cfg_ItemUpgrade::mutable_rows(int index) {
  // @@protoc_insertion_point(field_mutable:Cfg_ItemUpgrade.rows)
  return rows_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row >*
Cfg_ItemUpgrade::mutable_rows() {
  // @@protoc_insertion_point(field_mutable_list:Cfg_ItemUpgrade.rows)
  return &rows_;
}
inline const ::Cfg_ItemUpgrade_Row& Cfg_ItemUpgrade::_internal_rows(int index) const {
  return rows_.Get(index);
}
inline const ::Cfg_ItemUpgrade_Row& Cfg_ItemUpgrade::rows(int index) const {
  // @@protoc_insertion_point(field_get:Cfg_ItemUpgrade.rows)
  return _internal_rows(index);
}
inline ::Cfg_ItemUpgrade_Row* Cfg_ItemUpgrade::_internal_add_rows() {
  return rows_.Add();
}
inline ::Cfg_ItemUpgrade_Row* Cfg_ItemUpgrade::add_rows() {
  // @@protoc_insertion_point(field_add:Cfg_ItemUpgrade.rows)
  return _internal_add_rows();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Cfg_ItemUpgrade_Row >&
Cfg_ItemUpgrade::rows() const {
  // @@protoc_insertion_point(field_list:Cfg_ItemUpgrade.rows)
  return rows_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_config_2fCfg_5fItemUpgrade_2eproto
