// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/Cfg_BornPos.proto

#include "config/Cfg_BornPos.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_config_2fCfg_5fBornPos_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto;
class Cfg_BornPos_RowDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Cfg_BornPos_Row> _instance;
} _Cfg_BornPos_Row_default_instance_;
class Cfg_BornPosDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Cfg_BornPos> _instance;
} _Cfg_BornPos_default_instance_;
static void InitDefaultsscc_info_Cfg_BornPos_config_2fCfg_5fBornPos_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Cfg_BornPos_default_instance_;
    new (ptr) ::Cfg_BornPos();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Cfg_BornPos::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Cfg_BornPos_config_2fCfg_5fBornPos_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Cfg_BornPos_config_2fCfg_5fBornPos_2eproto}, {
      &scc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto.base,}};

static void InitDefaultsscc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Cfg_BornPos_Row_default_instance_;
    new (ptr) ::Cfg_BornPos_Row();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Cfg_BornPos_Row::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_config_2fCfg_5fBornPos_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_config_2fCfg_5fBornPos_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_config_2fCfg_5fBornPos_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_config_2fCfg_5fBornPos_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, id_),
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, prof_),
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, mapid_),
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, posx_),
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, posy_),
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, range_),
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos_Row, face_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Cfg_BornPos, rows_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Cfg_BornPos_Row)},
  { 12, -1, sizeof(::Cfg_BornPos)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Cfg_BornPos_Row_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_Cfg_BornPos_default_instance_),
};

const char descriptor_table_protodef_config_2fCfg_5fBornPos_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030config/Cfg_BornPos.proto\"\226\001\n\013Cfg_BornP"
  "os\022\036\n\004rows\030\001 \003(\0132\020.Cfg_BornPos.Row\032g\n\003Ro"
  "w\022\n\n\002id\030\001 \001(\r\022\014\n\004prof\030\002 \001(\r\022\r\n\005mapid\030\003 \001"
  "(\r\022\014\n\004posx\030\004 \001(\002\022\014\n\004posy\030\005 \001(\002\022\r\n\005range\030"
  "\006 \001(\002\022\014\n\004face\030\007 \001(\002B\002H\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_config_2fCfg_5fBornPos_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_config_2fCfg_5fBornPos_2eproto_sccs[2] = {
  &scc_info_Cfg_BornPos_config_2fCfg_5fBornPos_2eproto.base,
  &scc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_config_2fCfg_5fBornPos_2eproto_once;
static bool descriptor_table_config_2fCfg_5fBornPos_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_config_2fCfg_5fBornPos_2eproto = {
  &descriptor_table_config_2fCfg_5fBornPos_2eproto_initialized, descriptor_table_protodef_config_2fCfg_5fBornPos_2eproto, "config/Cfg_BornPos.proto", 191,
  &descriptor_table_config_2fCfg_5fBornPos_2eproto_once, descriptor_table_config_2fCfg_5fBornPos_2eproto_sccs, descriptor_table_config_2fCfg_5fBornPos_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_config_2fCfg_5fBornPos_2eproto::offsets,
  file_level_metadata_config_2fCfg_5fBornPos_2eproto, 2, file_level_enum_descriptors_config_2fCfg_5fBornPos_2eproto, file_level_service_descriptors_config_2fCfg_5fBornPos_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_config_2fCfg_5fBornPos_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_config_2fCfg_5fBornPos_2eproto), true);

// ===================================================================

void Cfg_BornPos_Row::InitAsDefaultInstance() {
}
class Cfg_BornPos_Row::_Internal {
 public:
};

Cfg_BornPos_Row::Cfg_BornPos_Row()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_BornPos.Row)
}
Cfg_BornPos_Row::Cfg_BornPos_Row(const Cfg_BornPos_Row& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&face_) -
    reinterpret_cast<char*>(&id_)) + sizeof(face_));
  // @@protoc_insertion_point(copy_constructor:Cfg_BornPos.Row)
}

void Cfg_BornPos_Row::SharedCtor() {
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&face_) -
      reinterpret_cast<char*>(&id_)) + sizeof(face_));
}

Cfg_BornPos_Row::~Cfg_BornPos_Row() {
  // @@protoc_insertion_point(destructor:Cfg_BornPos.Row)
  SharedDtor();
}

void Cfg_BornPos_Row::SharedDtor() {
}

void Cfg_BornPos_Row::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Cfg_BornPos_Row& Cfg_BornPos_Row::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Cfg_BornPos_Row_config_2fCfg_5fBornPos_2eproto.base);
  return *internal_default_instance();
}


void Cfg_BornPos_Row::InternalSwap(Cfg_BornPos_Row* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Cfg_BornPos_Row::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void Cfg_BornPos::InitAsDefaultInstance() {
}
class Cfg_BornPos::_Internal {
 public:
};

Cfg_BornPos::Cfg_BornPos()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_BornPos)
}
Cfg_BornPos::Cfg_BornPos(const Cfg_BornPos& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr),
      rows_(from.rows_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Cfg_BornPos)
}

void Cfg_BornPos::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Cfg_BornPos_config_2fCfg_5fBornPos_2eproto.base);
}

Cfg_BornPos::~Cfg_BornPos() {
  // @@protoc_insertion_point(destructor:Cfg_BornPos)
  SharedDtor();
}

void Cfg_BornPos::SharedDtor() {
}

void Cfg_BornPos::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Cfg_BornPos& Cfg_BornPos::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Cfg_BornPos_config_2fCfg_5fBornPos_2eproto.base);
  return *internal_default_instance();
}


void Cfg_BornPos::InternalSwap(Cfg_BornPos* other) {
  using std::swap;
  GetReflection()->Swap(this, other);}

::PROTOBUF_NAMESPACE_ID::Metadata Cfg_BornPos::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Cfg_BornPos_Row* Arena::CreateMaybeMessage< ::Cfg_BornPos_Row >(Arena* arena) {
  return Arena::CreateInternal< ::Cfg_BornPos_Row >(arena);
}
template<> PROTOBUF_NOINLINE ::Cfg_BornPos* Arena::CreateMaybeMessage< ::Cfg_BornPos >(Arena* arena) {
  return Arena::CreateInternal< ::Cfg_BornPos >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
