// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config/Cfg_Scene_Patrol.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "config/Cfg_Scene_Patrol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* Cfg_Scene_Patrol_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Cfg_Scene_Patrol_reflection_ = NULL;
const ::google::protobuf::Descriptor* Cfg_Scene_Patrol_Row_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Cfg_Scene_Patrol_Row_reflection_ = NULL;
const ::google::protobuf::Descriptor* Cfg_Scene_Patrol_Row_patrol_data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Cfg_Scene_Patrol_Row_patrol_data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_config_2fCfg_5fScene_5fPatrol_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_config_2fCfg_5fScene_5fPatrol_2eproto() {
  protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "config/Cfg_Scene_Patrol.proto");
  GOOGLE_CHECK(file != NULL);
  Cfg_Scene_Patrol_descriptor_ = file->message_type(0);
  static const int Cfg_Scene_Patrol_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol, rows_),
  };
  Cfg_Scene_Patrol_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Cfg_Scene_Patrol_descriptor_,
      Cfg_Scene_Patrol::internal_default_instance(),
      Cfg_Scene_Patrol_offsets_,
      -1,
      -1,
      -1,
      sizeof(Cfg_Scene_Patrol),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol, _internal_metadata_));
  Cfg_Scene_Patrol_Row_descriptor_ = Cfg_Scene_Patrol_descriptor_->nested_type(0);
  static const int Cfg_Scene_Patrol_Row_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row, idmap_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row, patrol_idx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row, patrol_type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row, data_),
  };
  Cfg_Scene_Patrol_Row_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Cfg_Scene_Patrol_Row_descriptor_,
      Cfg_Scene_Patrol_Row::internal_default_instance(),
      Cfg_Scene_Patrol_Row_offsets_,
      -1,
      -1,
      -1,
      sizeof(Cfg_Scene_Patrol_Row),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row, _internal_metadata_));
  Cfg_Scene_Patrol_Row_patrol_data_descriptor_ = Cfg_Scene_Patrol_Row_descriptor_->nested_type(0);
  static const int Cfg_Scene_Patrol_Row_patrol_data_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row_patrol_data, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row_patrol_data, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row_patrol_data, wait_ms_min_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row_patrol_data, wait_ms_max_),
  };
  Cfg_Scene_Patrol_Row_patrol_data_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Cfg_Scene_Patrol_Row_patrol_data_descriptor_,
      Cfg_Scene_Patrol_Row_patrol_data::internal_default_instance(),
      Cfg_Scene_Patrol_Row_patrol_data_offsets_,
      -1,
      -1,
      -1,
      sizeof(Cfg_Scene_Patrol_Row_patrol_data),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Cfg_Scene_Patrol_Row_patrol_data, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_config_2fCfg_5fScene_5fPatrol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Cfg_Scene_Patrol_descriptor_, Cfg_Scene_Patrol::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Cfg_Scene_Patrol_Row_descriptor_, Cfg_Scene_Patrol_Row::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Cfg_Scene_Patrol_Row_patrol_data_descriptor_, Cfg_Scene_Patrol_Row_patrol_data::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_config_2fCfg_5fScene_5fPatrol_2eproto() {
  Cfg_Scene_Patrol_default_instance_.Shutdown();
  delete Cfg_Scene_Patrol_reflection_;
  Cfg_Scene_Patrol_Row_default_instance_.Shutdown();
  delete Cfg_Scene_Patrol_Row_reflection_;
  Cfg_Scene_Patrol_Row_patrol_data_default_instance_.Shutdown();
  delete Cfg_Scene_Patrol_Row_patrol_data_reflection_;
}

void protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  Cfg_Scene_Patrol_default_instance_.DefaultConstruct();
  Cfg_Scene_Patrol_Row_default_instance_.DefaultConstruct();
  Cfg_Scene_Patrol_Row_patrol_data_default_instance_.DefaultConstruct();
  Cfg_Scene_Patrol_default_instance_.get_mutable()->InitAsDefaultInstance();
  Cfg_Scene_Patrol_Row_default_instance_.get_mutable()->InitAsDefaultInstance();
  Cfg_Scene_Patrol_Row_patrol_data_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto_once_);
void protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto_once_,
                 &protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto_impl);
}
void protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035config/Cfg_Scene_Patrol.proto\"\367\001\n\020Cfg_"
    "Scene_Patrol\022#\n\004rows\030\001 \003(\0132\025.Cfg_Scene_P"
    "atrol.Row\032\275\001\n\003Row\022\r\n\005idmap\030\001 \001(\r\022\022\n\npatr"
    "ol_idx\030\002 \001(\r\022\023\n\013patrol_type\030\004 \001(\r\022/\n\004dat"
    "a\030\005 \003(\0132!.Cfg_Scene_Patrol.Row.patrol_da"
    "ta\032M\n\013patrol_data\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022"
    "\023\n\013wait_ms_min\030\003 \001(\r\022\023\n\013wait_ms_max\030\004 \001("
    "\rB\002H\002b\006proto3", 293);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "config/Cfg_Scene_Patrol.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_config_2fCfg_5fScene_5fPatrol_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto_once_);
void protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto_once_,
                 &protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_config_2fCfg_5fScene_5fPatrol_2eproto {
  StaticDescriptorInitializer_config_2fCfg_5fScene_5fPatrol_2eproto() {
    protobuf_AddDesc_config_2fCfg_5fScene_5fPatrol_2eproto();
  }
} static_descriptor_initializer_config_2fCfg_5fScene_5fPatrol_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Cfg_Scene_Patrol_Row_patrol_data::kXFieldNumber;
const int Cfg_Scene_Patrol_Row_patrol_data::kYFieldNumber;
const int Cfg_Scene_Patrol_Row_patrol_data::kWaitMsMinFieldNumber;
const int Cfg_Scene_Patrol_Row_patrol_data::kWaitMsMaxFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Cfg_Scene_Patrol_Row_patrol_data::Cfg_Scene_Patrol_Row_patrol_data()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_Scene_Patrol.Row.patrol_data)
}

void Cfg_Scene_Patrol_Row_patrol_data::InitAsDefaultInstance() {
}

Cfg_Scene_Patrol_Row_patrol_data::Cfg_Scene_Patrol_Row_patrol_data(const Cfg_Scene_Patrol_Row_patrol_data& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Cfg_Scene_Patrol.Row.patrol_data)
}

void Cfg_Scene_Patrol_Row_patrol_data::SharedCtor() {
  ::memset(&x_, 0, reinterpret_cast<char*>(&wait_ms_max_) -
    reinterpret_cast<char*>(&x_) + sizeof(wait_ms_max_));
  _cached_size_ = 0;
}

Cfg_Scene_Patrol_Row_patrol_data::~Cfg_Scene_Patrol_Row_patrol_data() {
  // @@protoc_insertion_point(destructor:Cfg_Scene_Patrol.Row.patrol_data)
  SharedDtor();
}

void Cfg_Scene_Patrol_Row_patrol_data::SharedDtor() {
}

void Cfg_Scene_Patrol_Row_patrol_data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Cfg_Scene_Patrol_Row_patrol_data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Cfg_Scene_Patrol_Row_patrol_data_descriptor_;
}

const Cfg_Scene_Patrol_Row_patrol_data& Cfg_Scene_Patrol_Row_patrol_data::default_instance() {
  protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Cfg_Scene_Patrol_Row_patrol_data> Cfg_Scene_Patrol_Row_patrol_data_default_instance_;

Cfg_Scene_Patrol_Row_patrol_data* Cfg_Scene_Patrol_Row_patrol_data::New(::google::protobuf::Arena* arena) const {
  Cfg_Scene_Patrol_Row_patrol_data* n = new Cfg_Scene_Patrol_Row_patrol_data;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Cfg_Scene_Patrol_Row_patrol_data::UnsafeMergeFrom(const Cfg_Scene_Patrol_Row_patrol_data& from) {
  MergeFrom(from);
}
void Cfg_Scene_Patrol_Row_patrol_data::Swap(Cfg_Scene_Patrol_Row_patrol_data* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Cfg_Scene_Patrol_Row_patrol_data::InternalSwap(Cfg_Scene_Patrol_Row_patrol_data* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Cfg_Scene_Patrol_Row_patrol_data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Cfg_Scene_Patrol_Row_patrol_data_descriptor_;
  metadata.reflection = Cfg_Scene_Patrol_Row_patrol_data_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Cfg_Scene_Patrol_Row::kIdmapFieldNumber;
const int Cfg_Scene_Patrol_Row::kPatrolIdxFieldNumber;
const int Cfg_Scene_Patrol_Row::kPatrolTypeFieldNumber;
const int Cfg_Scene_Patrol_Row::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Cfg_Scene_Patrol_Row::Cfg_Scene_Patrol_Row()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_Scene_Patrol.Row)
}

void Cfg_Scene_Patrol_Row::InitAsDefaultInstance() {
}

Cfg_Scene_Patrol_Row::Cfg_Scene_Patrol_Row(const Cfg_Scene_Patrol_Row& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Cfg_Scene_Patrol.Row)
}

void Cfg_Scene_Patrol_Row::SharedCtor() {
  ::memset(&idmap_, 0, reinterpret_cast<char*>(&patrol_type_) -
    reinterpret_cast<char*>(&idmap_) + sizeof(patrol_type_));
  _cached_size_ = 0;
}

Cfg_Scene_Patrol_Row::~Cfg_Scene_Patrol_Row() {
  // @@protoc_insertion_point(destructor:Cfg_Scene_Patrol.Row)
  SharedDtor();
}

void Cfg_Scene_Patrol_Row::SharedDtor() {
}

void Cfg_Scene_Patrol_Row::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Cfg_Scene_Patrol_Row::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Cfg_Scene_Patrol_Row_descriptor_;
}

const Cfg_Scene_Patrol_Row& Cfg_Scene_Patrol_Row::default_instance() {
  protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Cfg_Scene_Patrol_Row> Cfg_Scene_Patrol_Row_default_instance_;

Cfg_Scene_Patrol_Row* Cfg_Scene_Patrol_Row::New(::google::protobuf::Arena* arena) const {
  Cfg_Scene_Patrol_Row* n = new Cfg_Scene_Patrol_Row;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Cfg_Scene_Patrol_Row::UnsafeMergeFrom(const Cfg_Scene_Patrol_Row& from) {
  MergeFrom(from);
}
void Cfg_Scene_Patrol_Row::Swap(Cfg_Scene_Patrol_Row* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Cfg_Scene_Patrol_Row::InternalSwap(Cfg_Scene_Patrol_Row* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Cfg_Scene_Patrol_Row::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Cfg_Scene_Patrol_Row_descriptor_;
  metadata.reflection = Cfg_Scene_Patrol_Row_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Cfg_Scene_Patrol::kRowsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Cfg_Scene_Patrol::Cfg_Scene_Patrol()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:Cfg_Scene_Patrol)
}

void Cfg_Scene_Patrol::InitAsDefaultInstance() {
}

Cfg_Scene_Patrol::Cfg_Scene_Patrol(const Cfg_Scene_Patrol& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Cfg_Scene_Patrol)
}

void Cfg_Scene_Patrol::SharedCtor() {
  _cached_size_ = 0;
}

Cfg_Scene_Patrol::~Cfg_Scene_Patrol() {
  // @@protoc_insertion_point(destructor:Cfg_Scene_Patrol)
  SharedDtor();
}

void Cfg_Scene_Patrol::SharedDtor() {
}

void Cfg_Scene_Patrol::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Cfg_Scene_Patrol::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Cfg_Scene_Patrol_descriptor_;
}

const Cfg_Scene_Patrol& Cfg_Scene_Patrol::default_instance() {
  protobuf_InitDefaults_config_2fCfg_5fScene_5fPatrol_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Cfg_Scene_Patrol> Cfg_Scene_Patrol_default_instance_;

Cfg_Scene_Patrol* Cfg_Scene_Patrol::New(::google::protobuf::Arena* arena) const {
  Cfg_Scene_Patrol* n = new Cfg_Scene_Patrol;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Cfg_Scene_Patrol::UnsafeMergeFrom(const Cfg_Scene_Patrol& from) {
  MergeFrom(from);
}
void Cfg_Scene_Patrol::Swap(Cfg_Scene_Patrol* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Cfg_Scene_Patrol::InternalSwap(Cfg_Scene_Patrol* other) {
  GetReflection()->Swap(this, other);}

::google::protobuf::Metadata Cfg_Scene_Patrol::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Cfg_Scene_Patrol_descriptor_;
  metadata.reflection = Cfg_Scene_Patrol_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Cfg_Scene_Patrol_Row_patrol_data

// optional float x = 1;
void Cfg_Scene_Patrol_Row_patrol_data::clear_x() {
  x_ = 0;
}
float Cfg_Scene_Patrol_Row_patrol_data::x() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.patrol_data.x)
  return x_;
}
void Cfg_Scene_Patrol_Row_patrol_data::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.patrol_data.x)
}

// optional float y = 2;
void Cfg_Scene_Patrol_Row_patrol_data::clear_y() {
  y_ = 0;
}
float Cfg_Scene_Patrol_Row_patrol_data::y() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.patrol_data.y)
  return y_;
}
void Cfg_Scene_Patrol_Row_patrol_data::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.patrol_data.y)
}

// optional uint32 wait_ms_min = 3;
void Cfg_Scene_Patrol_Row_patrol_data::clear_wait_ms_min() {
  wait_ms_min_ = 0u;
}
::google::protobuf::uint32 Cfg_Scene_Patrol_Row_patrol_data::wait_ms_min() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.patrol_data.wait_ms_min)
  return wait_ms_min_;
}
void Cfg_Scene_Patrol_Row_patrol_data::set_wait_ms_min(::google::protobuf::uint32 value) {
  
  wait_ms_min_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.patrol_data.wait_ms_min)
}

// optional uint32 wait_ms_max = 4;
void Cfg_Scene_Patrol_Row_patrol_data::clear_wait_ms_max() {
  wait_ms_max_ = 0u;
}
::google::protobuf::uint32 Cfg_Scene_Patrol_Row_patrol_data::wait_ms_max() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.patrol_data.wait_ms_max)
  return wait_ms_max_;
}
void Cfg_Scene_Patrol_Row_patrol_data::set_wait_ms_max(::google::protobuf::uint32 value) {
  
  wait_ms_max_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.patrol_data.wait_ms_max)
}

inline const Cfg_Scene_Patrol_Row_patrol_data* Cfg_Scene_Patrol_Row_patrol_data::internal_default_instance() {
  return &Cfg_Scene_Patrol_Row_patrol_data_default_instance_.get();
}
// -------------------------------------------------------------------

// Cfg_Scene_Patrol_Row

// optional uint32 idmap = 1;
void Cfg_Scene_Patrol_Row::clear_idmap() {
  idmap_ = 0u;
}
::google::protobuf::uint32 Cfg_Scene_Patrol_Row::idmap() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.idmap)
  return idmap_;
}
void Cfg_Scene_Patrol_Row::set_idmap(::google::protobuf::uint32 value) {
  
  idmap_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.idmap)
}

// optional uint32 patrol_idx = 2;
void Cfg_Scene_Patrol_Row::clear_patrol_idx() {
  patrol_idx_ = 0u;
}
::google::protobuf::uint32 Cfg_Scene_Patrol_Row::patrol_idx() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.patrol_idx)
  return patrol_idx_;
}
void Cfg_Scene_Patrol_Row::set_patrol_idx(::google::protobuf::uint32 value) {
  
  patrol_idx_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.patrol_idx)
}

// optional uint32 patrol_type = 4;
void Cfg_Scene_Patrol_Row::clear_patrol_type() {
  patrol_type_ = 0u;
}
::google::protobuf::uint32 Cfg_Scene_Patrol_Row::patrol_type() const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.patrol_type)
  return patrol_type_;
}
void Cfg_Scene_Patrol_Row::set_patrol_type(::google::protobuf::uint32 value) {
  
  patrol_type_ = value;
  // @@protoc_insertion_point(field_set:Cfg_Scene_Patrol.Row.patrol_type)
}

// repeated .Cfg_Scene_Patrol.Row.patrol_data data = 5;
int Cfg_Scene_Patrol_Row::data_size() const {
  return data_.size();
}
void Cfg_Scene_Patrol_Row::clear_data() {
  data_.Clear();
}
const ::Cfg_Scene_Patrol_Row_patrol_data& Cfg_Scene_Patrol_Row::data(int index) const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.Row.data)
  return data_.Get(index);
}
::Cfg_Scene_Patrol_Row_patrol_data* Cfg_Scene_Patrol_Row::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:Cfg_Scene_Patrol.Row.data)
  return data_.Mutable(index);
}
::Cfg_Scene_Patrol_Row_patrol_data* Cfg_Scene_Patrol_Row::add_data() {
  // @@protoc_insertion_point(field_add:Cfg_Scene_Patrol.Row.data)
  return data_.Add();
}
::google::protobuf::RepeatedPtrField< ::Cfg_Scene_Patrol_Row_patrol_data >*
Cfg_Scene_Patrol_Row::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:Cfg_Scene_Patrol.Row.data)
  return &data_;
}
const ::google::protobuf::RepeatedPtrField< ::Cfg_Scene_Patrol_Row_patrol_data >&
Cfg_Scene_Patrol_Row::data() const {
  // @@protoc_insertion_point(field_list:Cfg_Scene_Patrol.Row.data)
  return data_;
}

inline const Cfg_Scene_Patrol_Row* Cfg_Scene_Patrol_Row::internal_default_instance() {
  return &Cfg_Scene_Patrol_Row_default_instance_.get();
}
// -------------------------------------------------------------------

// Cfg_Scene_Patrol

// repeated .Cfg_Scene_Patrol.Row rows = 1;
int Cfg_Scene_Patrol::rows_size() const {
  return rows_.size();
}
void Cfg_Scene_Patrol::clear_rows() {
  rows_.Clear();
}
const ::Cfg_Scene_Patrol_Row& Cfg_Scene_Patrol::rows(int index) const {
  // @@protoc_insertion_point(field_get:Cfg_Scene_Patrol.rows)
  return rows_.Get(index);
}
::Cfg_Scene_Patrol_Row* Cfg_Scene_Patrol::mutable_rows(int index) {
  // @@protoc_insertion_point(field_mutable:Cfg_Scene_Patrol.rows)
  return rows_.Mutable(index);
}
::Cfg_Scene_Patrol_Row* Cfg_Scene_Patrol::add_rows() {
  // @@protoc_insertion_point(field_add:Cfg_Scene_Patrol.rows)
  return rows_.Add();
}
::google::protobuf::RepeatedPtrField< ::Cfg_Scene_Patrol_Row >*
Cfg_Scene_Patrol::mutable_rows() {
  // @@protoc_insertion_point(field_mutable_list:Cfg_Scene_Patrol.rows)
  return &rows_;
}
const ::google::protobuf::RepeatedPtrField< ::Cfg_Scene_Patrol_Row >&
Cfg_Scene_Patrol::rows() const {
  // @@protoc_insertion_point(field_list:Cfg_Scene_Patrol.rows)
  return rows_;
}

inline const Cfg_Scene_Patrol* Cfg_Scene_Patrol::internal_default_instance() {
  return &Cfg_Scene_Patrol_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
