#ifndef GAMEEVENTDEF_H
#define GAMEEVENTDEF_H

enum GameEventType
{
    EVENTID_DELACTOR           = 100,
    EVENTID_FLYMAP             = 101,
    EVENTID_BROCAST_SHOW       = 102,
    EVENTID_SEND_ATTRIB_CHANGE = 103,

    EVENTID_BULLET_APPLY    = 201,
    EVENTID_BULLET_MOVESTEP = 202,
};
#endif /* GAMEEVENTDEF_H */
